### ISSUE TITLE
Suppress indent on newline after closing curly braces

### ISSUE THREAD

**Issue by heavywatal** [REditorSupport/atom-language-r#15]
When I hit the return key right after a closing brace,
```r
for (i in seq_len(3L)) {
  print(i)
}|
```

I expect no indent:
```r
for (i in seq_len(3L)) {
  print(i)
}
|
```

But atom-languege-r 1.3.0 makes extra indent:
```r
for (i in seq_len(3L)) {
  print(i)
  }
  |
```

Interestingly, `command-z` has to be done twice to undo this change. Thanks.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6

**Comment by guillaumechaumet** [comment]
I'm a bit puzzled by this javascript bug

**Comment by heavywatal** [comment]
How about removing the #4 related code tentatively from `master`, and creating a new branch for it? So we can keep `master` clean until we figure out what is wrong with it. I would be happy to make a PR  for that.
