### ISSUE TITLE
Missing scopes on punctuation

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/atom-language-r#7]
_From @chbk on December 7, 2017 23:28_

I use r a lot so this package is great, is it still being developed?

If so, I noticed missing scopes on `()` `,`:
```r
sub("_", "", path)
getrootdir(utils::untar(src))
data.frame()
file.exists()
```
They should be `punctuation.definition.parameters.bracket.round.begin|end`, `punctuation.separator.parameters.comma` based on [docs](https://github.com/atom/flight-manual.atom.io/pull/114).

_Copied from original issue: REditorSupport/atom-language-r-legacy#10_

**Comment by randy3k** [comment]
I am sure that @kylebarron and @guillaumechaumet are still working on it.

**Comment by randy3k** [comment]
_From @kylebarron on December 8, 2017 0:31_

I've been focusing my efforts recently on Stata packages ([1](atom.io/packages/language-stata), [2](https://atom.io/packages/stata-exec)) since I'm required to use that language most of the time in my work. I hope to find time to work on this in the next month or two.

Also note that this currently isn't the repository that [language-r](url) is sourced from. See [this issue](https://github.com/lee-dohm/language-r/issues/25) for relevant discussion.

I also just noticed that @lee-dohm archived that repository, so I'm not sure if there's any hope of ever having this copy becoming upstream. Creating a maintained fork might be hard to gain traction.

Thoughts @guillaumechaumet ?

**Comment by randy3k** [comment]
We are waiting @lee-dohm to transfer the ownership of his repo to REditorSupport so we can inherit the atom package name `language-r`. I hope that we have already convinced him and showed our interests in maintaining it.

**Comment by randy3k** [comment]
_From @guillaumechaumet on December 8, 2017 6:11_

I was working on backticks definition since I have seen some strange behaviour. I will look into language-ruby to find some good examples.

**Comment by randy3k** [comment]
_From @guillaumechaumet on January 9, 2018 17:16_

I try to improve r.cson for punctuation definition. I have still an issue with back-tick scope. For example \`#variable\` appeared as comment where '#variable' don't. Any solution?

**Comment by randy3k** [comment]
it was fixed on the current master.

**Comment by chbk** [comment]
@randy3k It's still not working for me

**Comment by randy3k** [comment]
You are right, I misunderstood the issue.

**Comment by randy3k** [comment]
It should really be fixed now.

**Comment by chbk** [comment]
Awesome, thank you!

I just found other missing scopes on commas and semicolons that weren't in the original bug report:
```r
df[1,2];
a[,"weight"];
ifelse(p > median(p), "large", "small");
matrix(c(rep(1:0,3), rep(0:1,3)), ncol=2, byrow=TRUE);
```
Should I open a new issue for this?

**Comment by guillaumechaumet** [comment]
You should. But I don't see the point here. Could you give us a normal behavior?

**Comment by chbk** [comment]
Looks like it's actually a regression:

Before (1.4.0):
![before](https://user-images.githubusercontent.com/7478535/39231507-96a1509e-486a-11e8-9e88-79ecc83655a9.png)
After:
![after](https://user-images.githubusercontent.com/7478535/39231701-32e0b5d0-486b-11e8-82d3-0e27abf26ec5.png)

Semicolons should be `punctuation.terminator.semicolon`.
Commas should be `punctuation.separator.delimiter.comma` inside brackets and `punctuation.separator.parameters.comma` in function calls.

**Comment by guillaumechaumet** [comment]
Correction done
